# Site settings
title: Implementing Innovation, A User's Manual for Open Government Programs
email: hello@reboot.org
description: "​Implementing Innovation: A User’s Manual for Open Government Programs is a hands-on resource that provides practical advice and guidance for government changemakers as they navigate the specific challenges of implementing innovative programs in the public sector."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Reboot

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/thereboot
  - title: facebook
    url: https://www.facebook.com/Reboot-105224249553575/

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: _sass
  style: compressed

baseurl: /implementinginnovation

gems:
  - octopress-autoprefixer